language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get install -qq samtools
    - sudo apt-get install -qq bwa

install: "pip install -r requirements.txt"

script: "python ProDuSe/adapter_predict.py -i test/test5/wv_R1.fastq test/test5/wv_R2.fastq"
