dist: trusty
sudo: required

language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
# Enable python 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
    - sudo apt-get install -qq bwa
    - wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
    - bzip2 -d samtools-1.3.1.tar.bz2
    - tar -xf samtools-1.3.1.tar
    - cd samtools-1.3.1
    - sudo ./configure
    - sudo make
    - sudo make install
    - cd ..

install: 
    - "pip install -r requirements.txt"
    - python setup.py install

script:
    - "python ProDuSe/ProdusePipeline.py -c etc/produse_config.ini"
    - "python ProDuSe/ProdusePipeline.py -c etc/produse_config.ini -j 2 --directory_name Multithread --bwa $(which bwa) --samtools $(which samtools) --cleanup"
    - "produse run_produse -c etc/produse_config.ini --directory_name Installed -j 4 --trim_other_end"
    - "produse resume_produse -d Installed"
